version: 0.2
phases:
    install:
        commands:
            - sudo apt-get update && sudo apt-get install -y zip
    build:
        commands:
            - cd auth-redirect && pip install -r requirements.txt && zip -r ../auth-redirect.zip . && cd ..
            - cd auth-welcome && pip install -r requirements.txt && zip -r ../auth-welcome.zip . && cd ..
            - cd bank-bot && pip install -r requirements.txt && zip -r ../bank-bot.zip . && cd ..
            - cd facebook-webhook && pip install -r requirements.txt && zip -r ../facebook-webhook.zip . && cd ..
    post_build:
        commands:
            - aws s3 cp *.zip s3://khk-aws/demos/bank-bot-demo/
artifacts:
    type: zip
    files:
        - auth-redirect.zip
        - auth-welcome.zip
        - bank-bot.zip
        - facebook-webhook.zip
