version: 0.2
phases:
    install:
        commands:
            - sudo apt-get update && sudo apt-get install -y zip
    build:
        commands:
            - cd auth-redirect && pip install -r requirements.txt -t . && zip -r ../auth-redirect.zip . && cd ..
            - cd auth-welcome && pip install -r requirements.txt -t . && zip -r ../auth-welcome.zip . && cd ..
            - cd bank-bot && pip install -r requirements.txt -t . && zip -r ../bank-bot.zip . && cd ..
            - cd facebook-webhook && pip install -r requirements.txt -t . && zip -r ../facebook-webhook.zip . && cd ..
            - cd bank-backend && zip -r ../bank-backend.zip . && cd ..
    post_build:
        commands:
            - aws s3 cp auth-redirect.zip s3://khk-us-east-1/demos/bank-bot-demo/
            - aws s3 cp auth-welcome.zip s3://khk-us-east-1/demos/bank-bot-demo/
            - aws s3 cp bank-bot.zip s3://khk-us-east-1/demos/bank-bot-demo/
            - aws s3 cp facebook-webhook.zip s3://khk-us-east-1/demos/bank-bot-demo/
            - aws s3 cp bank-backend.zip s3://khk-us-east-1/demos/bank-bot-demo/

artifacts:
    type: zip
    files:
        - auth-redirect.zip
        - auth-welcome.zip
        - bank-bot.zip
        - facebook-webhook.zip
        - bank-backend.zip
        - cfn.yaml
